import { LmsMockData } from "./types";

export const lmsMockData: LmsMockData = {
  menus: [
    { key: "dashboard", label: "대시보드", description: "운영 현황 요약", group: "운영 관리" },
    {
      key: "students",
      label: "학생회원 관리",
      description: "학생 목록 및 상태",
      group: "운영 관리",
      badge: { text: "3", tone: "danger" },
    },
    {
      key: "class-records",
      label: "수업기록",
      description: "수업별 관찰 기록",
      group: "운영 관리",
      badge: { text: "NEW", tone: "primary" },
    },
    {
      key: "lessons",
      label: "강의 관리",
      description: "영상/음성/PDF",
      group: "강의 콘텐츠",
      badge: { text: "NEW", tone: "primary" },
    },
    { key: "assignments", label: "과제 관리", description: "과제 등록 및 진행", group: "강의 콘텐츠" },
    { key: "submit", label: "과제 제출", description: "원고/파일 제출 화면", group: "강의 콘텐츠" },
    {
      key: "feedback",
      label: "첨삭 관리",
      description: "첨삭 대기 및 코멘트",
      group: "첨삭 & 성장",
      badge: { text: "5", tone: "warning" },
    },
    { key: "growth", label: "성장지표", description: "역량 추이 확인", group: "첨삭 & 성장" },
    { key: "portfolio", label: "포트폴리오", description: "학생 성과 모음", group: "첨삭 & 성장" },
    { key: "parent-report", label: "학부모 리포트", description: "요약 리포트", group: "첨삭 & 성장" },
    { key: "board", label: "게시판", description: "공지/안내", group: "기타" },
    { key: "settings", label: "설정", description: "학원/알림 설정", group: "기타" },
  ],
  dashboardStats: [
    { label: "전체 학생", value: "142", delta: "이번달 +8명", tone: "primary" },
    { label: "과제 제출률", value: "87%", delta: "지난주 +3%", tone: "success" },
    { label: "첨삭 대기", value: "5", delta: "긴급 2건", tone: "warning" },
    { label: "이번주 출석률", value: "94%", delta: "38/40명", tone: "primary" },
  ],
  careStudents: [
    {
      id: "s-01",
      name: "신동현",
      grade: "고3",
      className: "수능 C반",
      teacher: "이선생님",
      submissionRate: 40,
      attendance: "주의",
      recentFeedback: "결석 2회 · 제출률 40%",
      enrollmentStatus: "상담필요",
    },
    {
      id: "s-02",
      name: "박지호",
      grade: "중2",
      className: "중등 A반",
      teacher: "박선생님",
      submissionRate: 60,
      attendance: "주의",
      recentFeedback: "지각 3회 · 미제출 1건",
      enrollmentStatus: "수강중",
    },
    {
      id: "s-03",
      name: "오하린",
      grade: "고1",
      className: "고1 기초 B",
      teacher: "김선생님",
      submissionRate: 68,
      attendance: "주의",
      recentFeedback: "성장 정체 3개월",
      enrollmentStatus: "상담필요",
    },
  ],
  feedbackQueue: [
    { id: "f-01", studentName: "신동현", assignmentTitle: "6월 2주차 논술 (이미지)", submittedAt: "52h", urgency: "높음" },
    { id: "f-02", studentName: "오하린", assignmentTitle: "독서감상문 (텍스트)", submittedAt: "28h", urgency: "일반" },
    { id: "f-03", studentName: "강민서", assignmentTitle: "시사논술 (PDF)", submittedAt: "14h", urgency: "일반" },
    { id: "f-04", studentName: "박지호", assignmentTitle: "경제논술 (텍스트)", submittedAt: "8h", urgency: "일반" },
  ],
  weeklySchedules: [
    { id: "w-01", day: "월 · 화", title: "중등 논술 기초 A반", teacher: "박선생님", room: "오후 3시" },
    { id: "w-02", day: "수 · 목", title: "고등 심화 논술 B반", teacher: "김선생님", room: "오후 4시" },
    { id: "w-03", day: "토", title: "수능 논술 특강 C반", teacher: "이선생님", room: "오전 10시" },
  ],
  students: [
    {
      id: "s-11",
      name: "최예린",
      grade: "고2",
      className: "고2 심화 A",
      teacher: "이수정",
      submissionRate: 92,
      attendance: "양호",
      recentFeedback: "논거 강화 필요",
      enrollmentStatus: "수강중",
    },
    {
      id: "s-12",
      name: "강지우",
      grade: "고1",
      className: "고1 기초 B",
      teacher: "정하늘",
      submissionRate: 78,
      attendance: "양호",
      recentFeedback: "구조는 안정적",
      enrollmentStatus: "수강중",
    },
    {
      id: "s-13",
      name: "윤서진",
      grade: "중3",
      className: "중3 예비반",
      teacher: "한지민",
      submissionRate: 64,
      attendance: "주의",
      recentFeedback: "근거 보강 필요",
      enrollmentStatus: "상담필요",
    },
  ],
  classRecord: {
    classDate: "2026-06-07",
    classTitle: "고2 심화 논술 - 사회 이슈 분석",
    goal: "주장-근거-반론 구조를 3단락으로 완성한다.",
    assignment: "신문 사설 비평문 1000자 작성",
    rows: [
      {
        studentName: "최예린",
        attendance: "출석",
        focus: 88,
        comprehension: 82,
        participation: 76,
        assignmentStatus: "완료",
        memo: "주장 근거 연결이 좋아짐",
      },
      {
        studentName: "김민서",
        attendance: "지각",
        focus: 65,
        comprehension: 70,
        participation: 58,
        assignmentStatus: "지연",
        memo: "도입부 작성 속도 개선 필요",
      },
    ],
    teacherMemo:
      "전반적으로 반론 제시의 질은 개선되고 있으나, 결론 단락에서 핵심 메시지 요약이 부족합니다. 다음 시간에는 결론 템플릿을 반복 훈련합니다.",
  },
  contents: [
    { id: "c-01", type: "영상", title: "논술 구조화 기본편", visibility: "공개", learners: 92, engagementRate: 81 },
    { id: "c-02", type: "음성", title: "첨삭 피드백 해설", visibility: "비공개", learners: 48, engagementRate: 73 },
    { id: "c-03", type: "PDF", title: "기출 분석 워크북", visibility: "공개", learners: 104, engagementRate: 88 },
  ],
  assignments: [
    {
      id: "a-01",
      title: "사회 이슈 비평문",
      kind: "논술",
      target: "고2 심화 A",
      dueDate: "2026-06-10",
      submitStatus: "18/22 제출",
      aiStatus: "완료",
      progress: "진행중",
    },
    {
      id: "a-02",
      title: "신문 사설 요약",
      kind: "요약",
      target: "고1 기초 B",
      dueDate: "2026-06-12",
      submitStatus: "9/20 제출",
      aiStatus: "대기",
      progress: "마감임박",
    },
  ],
  submitGuide: {
    assignmentTitle: "사회 이슈 비평문 초안 제출",
    dueDate: "2026-06-10 23:59",
    minChars: 800,
    maxChars: 1200,
  },
  feedback: {
    queue: [
      { id: "fq-01", studentName: "최예린", assignmentTitle: "사회 이슈 비평문", submittedAt: "09:10", urgency: "높음" },
      { id: "fq-02", studentName: "강지우", assignmentTitle: "신문 사설 요약", submittedAt: "10:45", urgency: "일반" },
    ],
    manuscript:
      "현대 사회에서 알고리즘 추천 시스템은 정보 접근을 돕는 장점이 있으나, 동시에 개인의 사고를 편향된 방향으로 고정할 위험이 있다. 특히 청소년의 경우 다양한 관점을 접할 기회가 줄어들 수 있으며...",
    aiAnalysis: [
      "논리 구조 점수 78/100 - 서론과 본론 연결은 안정적",
      "근거 다양성 62/100 - 통계/사례 보강 권장",
      "문장 표현 84/100 - 가독성 우수, 일부 반복 표현 존재",
    ],
  },
  growth: [
    { studentName: "최예린", logic: 82, expression: 88, reading: 79, consistency: 90 },
    { studentName: "강지우", logic: 74, expression: 71, reading: 76, consistency: 80 },
    { studentName: "윤서진", logic: 66, expression: 69, reading: 72, consistency: 64 },
  ],
  portfolio: [
    {
      id: "p-01",
      studentName: "최예린",
      assignmentTitle: "사회 이슈 비평문",
      month: "2026-06",
      score: 89,
      feedbackSummary: "논거 전개가 명확하고 반론 대응이 개선됨",
    },
    {
      id: "p-02",
      studentName: "강지우",
      assignmentTitle: "신문 사설 요약",
      month: "2026-06",
      score: 78,
      feedbackSummary: "핵심 요약은 좋으나 결론 압축이 필요",
    },
  ],
  parentReport: {
    studentName: "최예린",
    attendanceRate: 96,
    assignmentRate: 92,
    feedbackDone: 11,
    growthScore: 85,
  },
  board: [
    { id: "b-01", title: "6월 모의 논술 일정 안내", target: "전체 학생", createdAt: "2026-06-05", visibility: "공개" },
    { id: "b-02", title: "학부모 상담 주간 공지", target: "학부모", createdAt: "2026-06-03", visibility: "공개" },
    { id: "b-03", title: "강사 워크숍 자료 업로드", target: "강사", createdAt: "2026-06-01", visibility: "비공개" },
  ],
};
